In [218]:
import pandas as pd

In [220]:
df = pd.read_csv("NBA_games.csv", index_col=0)

In [222]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
1,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
2,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
3,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
4,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,240.0,240.0,40.0,94.0,0.426,14.0,32.0,0.438,26.0,32.0,...,100.0,32.2,230.0,136.0,IND,109,0,2025,2025-06-16,True
25680,240.0,240.0,31.0,74.0,0.419,8.0,30.0,0.267,21.0,26.0,...,100.0,28.4,177.0,102.0,IND,108,1,2025,2025-06-19,False
25681,240.0,240.0,38.0,92.0,0.413,15.0,42.0,0.357,17.0,25.0,...,38.1,44.1,186.0,114.0,OKC,91,0,2025,2025-06-19,True
25682,240.0,240.0,29.0,70.0,0.414,11.0,28.0,0.393,22.0,29.0,...,100.0,82.8,162.0,114.0,OKC,103,1,2025,2025-06-22,False
25683,240.0,240.0,35.0,87.0,0.402,11.0,40.0,0.275,22.0,31.0,...,53.2,42.5,134.0,123.0,IND,91,0,2025,2025-06-22,True

In [224]:
df = df.sort_values("date")

In [226]:
df = df.reset_index(drop=True)

In [228]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
1,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
2,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
3,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
4,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,240.0,240.0,40.0,94.0,0.426,14.0,32.0,0.438,26.0,32.0,...,100.0,32.2,230.0,136.0,IND,109,0,2025,2025-06-16,True
25680,240.0,240.0,31.0,74.0,0.419,8.0,30.0,0.267,21.0,26.0,...,100.0,28.4,177.0,102.0,IND,108,1,2025,2025-06-19,False
25681,240.0,240.0,38.0,92.0,0.413,15.0,42.0,0.357,17.0,25.0,...,38.1,44.1,186.0,114.0,OKC,91,0,2025,2025-06-19,True
25682,240.0,240.0,29.0,70.0,0.414,11.0,28.0,0.393,22.0,29.0,...,100.0,82.8,162.0,114.0,OKC,103,1,2025,2025-06-22,False
25683,240.0,240.0,35.0,87.0,0.402,11.0,40.0,0.275,22.0,31.0,...,53.2,42.5,134.0,123.0,IND,91,0,2025,2025-06-22,True

In [230]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [232]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
4,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,240.0,40.0,94.0,0.426,14.0,32.0,0.438,26.0,32.0,0.813,...,100.0,32.2,230.0,136.0,IND,109,0,2025,2025-06-16,True
25680,240.0,31.0,74.0,0.419,8.0,30.0,0.267,21.0,26.0,0.808,...,100.0,28.4,177.0,102.0,IND,108,1,2025,2025-06-19,False
25681,240.0,38.0,92.0,0.413,15.0,42.0,0.357,17.0,25.0,0.680,...,38.1,44.1,186.0,114.0,OKC,91,0,2025,2025-06-19,True
25682,240.0,29.0,70.0,0.414,11.0,28.0,0.393,22.0,29.0,0.759,...,100.0,82.8,162.0,114.0,OKC,103,1,2025,2025-06-22,False
25683,240.0,35.0,87.0,0.402,11.0,40.0,0.275,22.0,31.0,0.710,...,53.2,42.5,134.0,123.0,IND,91,0,2025,2025-06-22,True

In [234]:
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1127067056.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby("team", group_keys=False).apply(add_target)

In [236]:
df[df["team"] == "CHI"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,True
23,240.0,42.0,78.0,0.538,14.0,28.0,0.500,17.0,20.0,0.850,...,29.7,123.0,124.0,BRK,100,1,2016,2015-10-28,True,False
55,265.0,34.0,84.0,0.405,7.0,22.0,0.318,19.0,26.0,0.731,...,33.7,133.0,95.0,DET,98,1,2016,2015-10-30,False,True
85,240.0,33.0,87.0,0.379,7.0,28.0,0.250,19.0,22.0,0.864,...,34.7,132.0,109.0,ORL,87,0,2016,2015-11-01,True,False
116,240.0,44.0,90.0,0.489,14.0,30.0,0.467,3.0,8.0,0.375,...,41.3,176.0,113.0,CHO,130,1,2016,2015-11-03,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25409,240.0,41.0,86.0,0.477,15.0,43.0,0.349,16.0,19.0,0.842,...,59.2,249.0,124.0,CLE,135,1,2025,2025-04-08,False,True
25432,240.0,46.0,89.0,0.517,14.0,37.0,0.378,13.0,13.0,1.000,...,35.8,151.0,125.0,MIA,111,0,2025,2025-04-09,True,True
25467,240.0,43.0,93.0,0.462,13.0,41.0,0.317,20.0,22.0,0.909,...,28.8,112.0,121.0,WAS,89,0,2025,2025-04-11,True,True
25479,240.0,47.0,103.0,0.456,13.0,40.0,0.325,15.0,20.0,0.750,...,36.1,131.0,123.0,PHI,102,1,2025,2025-04-13,True,False
25510,240.0,33.0,83.0,0.398,10.0,37.0,0.270,14.0,17.0,0.824,...,36.5,145.0,103.0,MIA,109,0,2025,2025-04-16,False,NaN

In [238]:
df["target"][pd.isnull(df["target"])] = 2

C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1618397414.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["target"][pd.isnull(df["target"])] = 2
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [240]:
df["target"] = df["target"].astype(int, errors="ignore")

In [242]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
4,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,240.0,40.0,94.0,0.426,14.0,32.0,0.438,26.0,32.0,0.813,...,32.2,230.0,136.0,IND,109,0,2025,2025-06-16,True,0
25680,240.0,31.0,74.0,0.419,8.0,30.0,0.267,21.0,26.0,0.808,...,28.4,177.0,102.0,IND,108,1,2025,2025-06-19,False,1
25681,240.0,38.0,92.0,0.413,15.0,42.0,0.357,17.0,25.0,0.680,...,44.1,186.0,114.0,OKC,91,0,2025,2025-06-19,True,0
25682,240.0,29.0,70.0,0.414,11.0,28.0,0.393,22.0,29.0,0.759,...,82.8,162.0,114.0,OKC,103,1,2025,2025-06-22,False,2
25683,240.0,35.0,87.0,0.402,11.0,40.0,0.275,22.0,31.0,0.710,...,42.5,134.0,123.0,IND,91,0,2025,2025-06-22,True,2

In [244]:
df["won"].value_counts()

won
True     12842
False    12842
Name: count, dtype: int64

In [246]:
df["target"].value_counts()

target
1    12828
0    12826
2       30
Name: count, dtype: int64

In [248]:
nulls = pd.isnull(df)
nulls = nulls.sum()
nulls = nulls[nulls > 0]

In [250]:
nulls

ft%                 1
gmsc            25684
+/-             25684
mp_max          25684
mp_max.1        25684
ft%_max             1
+/-_max            15
ft%_opp             1
gmsc_opp        25684
+/-_opp         25684
mp_max_opp      25684
mp_max_opp.1    25684
ft%_max_opp         1
+/-_max_opp        15
dtype: int64

In [252]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [254]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'orb',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=138)

In [256]:
df = df[valid_columns].copy()

In [258]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,23.0,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,7.0,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,11.0,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,7.0,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
4,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,8.0,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,240.0,40.0,94.0,0.426,14.0,32.0,0.438,26.0,32.0,19.0,...,32.2,230.0,136.0,IND,109,0,2025,2025-06-16,True,0
25680,240.0,31.0,74.0,0.419,8.0,30.0,0.267,21.0,26.0,4.0,...,28.4,177.0,102.0,IND,108,1,2025,2025-06-19,False,1
25681,240.0,38.0,92.0,0.413,15.0,42.0,0.357,17.0,25.0,11.0,...,44.1,186.0,114.0,OKC,91,0,2025,2025-06-19,True,0
25682,240.0,29.0,70.0,0.414,11.0,28.0,0.393,22.0,29.0,12.0,...,82.8,162.0,114.0,OKC,103,1,2025,2025-06-22,False,2
25683,240.0,35.0,87.0,0.402,11.0,40.0,0.275,22.0,31.0,13.0,...,42.5,134.0,123.0,IND,91,0,2025,2025-06-22,True,2

In [260]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [262]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

In [264]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [266]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.391304,0.529412,0.276190,0.413793,0.378788,0.491686,0.454545,0.406250,0.793103,...,0.151282,0.800948,0.473118,ATL,0.267857,1.0,2016,2015-10-27,True,1
1,0.0,0.391304,0.323529,0.433333,0.275862,0.348485,0.351544,0.272727,0.234375,0.241379,...,0.020513,0.203791,0.290323,DET,0.375000,0.0,2016,2015-10-27,False,1
2,0.0,0.413043,0.500000,0.321429,0.310345,0.378788,0.368171,0.227273,0.265625,0.379310,...,0.161538,0.345972,0.290323,CHI,0.294643,1.0,2016,2015-10-27,False,1
3,0.0,0.391304,0.397059,0.371429,0.241379,0.227273,0.437055,0.363636,0.359375,0.241379,...,0.089744,0.232227,0.301075,CLE,0.276786,0.0,2016,2015-10-27,True,1
4,0.0,0.347826,0.338235,0.364286,0.206897,0.212121,0.395487,0.431818,0.421875,0.275862,...,0.278205,0.554502,0.290323,GSW,0.419643,1.0,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,0.0,0.456522,0.500000,0.373810,0.482759,0.424242,0.520190,0.590909,0.500000,0.655172,...,0.130769,0.668246,0.634409,IND,0.401786,0.0,2025,2025-06-16,True,0
25680,0.0,0.260870,0.205882,0.357143,0.275862,0.393939,0.317102,0.477273,0.406250,0.137931,...,0.082051,0.417062,0.268817,IND,0.392857,1.0,2025,2025-06-19,False,1
25681,0.0,0.413043,0.470588,0.342857,0.517241,0.575758,0.423990,0.386364,0.390625,0.379310,...,0.283333,0.459716,0.397849,OKC,0.241071,0.0,2025,2025-06-19,True,0
25682,0.0,0.217391,0.147059,0.345238,0.379310,0.363636,0.466746,0.500000,0.453125,0.413793,...,0.779487,0.345972,0.397849,OKC,0.348214,1.0,2025,2025-06-22,False,2
25683,0.0,0.347826,0.397059,0.316667,0.379310,0.545455,0.326603,0.500000,0.484375,0.448276,...,0.262821,0.213270,0.494624,IND,0.241071,0.0,2025,2025-06-22,True,2

In [268]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [270]:
predictors = list(selected_columns[sfs.get_support()])

In [272]:
predictors

['ft',
 'orb%',
 'trb%',
 'tov%',
 'usg%',
 'fg_max',
 'fta_max',
 'orb_max',
 'gmsc_max',
 'drb%_max',
 'blk%_max',
 'usg%_max',
 'ortg_max',
 '3p_opp',
 'ast_opp',
 'stl_opp',
 'pts_opp',
 'drb%_opp',
 'trb%_opp',
 'usg%_opp',
 '3p%_max_opp',
 'ft_max_opp',
 'blk_max_opp',
 'orb%_max_opp',
 'trb%_max_opp',
 'stl%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp',
 'ortg_max_opp',
 'total_opp']

In [274]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []

    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = seasons[i]

        train = data[data["season"] < season]
        test = data[data["season"] == season] 

        model.fit(train[predictors], train["target"])
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index= test.index)

        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]

        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [276]:
predictions = backtest(df, rr, predictors)

In [278]:
predictions

       actual  prediction
5242        1           0
5243        0           0
5244        1           1
5245        1           0
5246        1           0
...       ...         ...
25679       0           1
25680       1           1
25681       0           1
25682       2           0
25683       2           1

[20442 rows x 2 columns]

In [280]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] !=2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.548108955516363

In [282]:
df.groupby(["home"]).apply(lambda x: x[x["won"]==1].shape[0] / x.shape[0])

C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\2527807349.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["home"]).apply(lambda x: x[x["won"]==1].shape[0] / x.shape[0])

home
0.0    0.432643
1.0    0.567357
dtype: float64

In [284]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.391304,0.529412,0.276190,0.413793,0.378788,0.491686,0.454545,0.406250,0.793103,...,0.151282,0.800948,0.473118,ATL,0.267857,1.0,2016,2015-10-27,True,1
1,0.0,0.391304,0.323529,0.433333,0.275862,0.348485,0.351544,0.272727,0.234375,0.241379,...,0.020513,0.203791,0.290323,DET,0.375000,0.0,2016,2015-10-27,False,1
2,0.0,0.413043,0.500000,0.321429,0.310345,0.378788,0.368171,0.227273,0.265625,0.379310,...,0.161538,0.345972,0.290323,CHI,0.294643,1.0,2016,2015-10-27,False,1
3,0.0,0.391304,0.397059,0.371429,0.241379,0.227273,0.437055,0.363636,0.359375,0.241379,...,0.089744,0.232227,0.301075,CLE,0.276786,0.0,2016,2015-10-27,True,1
4,0.0,0.347826,0.338235,0.364286,0.206897,0.212121,0.395487,0.431818,0.421875,0.275862,...,0.278205,0.554502,0.290323,GSW,0.419643,1.0,2016,2015-10-27,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,0.0,0.456522,0.500000,0.373810,0.482759,0.424242,0.520190,0.590909,0.500000,0.655172,...,0.130769,0.668246,0.634409,IND,0.401786,0.0,2025,2025-06-16,True,0
25680,0.0,0.260870,0.205882,0.357143,0.275862,0.393939,0.317102,0.477273,0.406250,0.137931,...,0.082051,0.417062,0.268817,IND,0.392857,1.0,2025,2025-06-19,False,1
25681,0.0,0.413043,0.470588,0.342857,0.517241,0.575758,0.423990,0.386364,0.390625,0.379310,...,0.283333,0.459716,0.397849,OKC,0.241071,0.0,2025,2025-06-19,True,0
25682,0.0,0.217391,0.147059,0.345238,0.379310,0.363636,0.466746,0.500000,0.453125,0.413793,...,0.779487,0.345972,0.397849,OKC,0.348214,1.0,2025,2025-06-22,False,2
25683,0.0,0.347826,0.397059,0.316667,0.379310,0.545455,0.326603,0.500000,0.484375,0.448276,...,0.262821,0.213270,0.494624,IND,0.241071,0.0,2025,2025-06-22,True,2

In [286]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [288]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.391304,0.529412,0.276190,0.413793,0.378788,0.491686,0.454545,0.406250,0.793103,...,0.071,0.550314,0.151282,0.800948,0.473118,0.267857,1.0,True,DET,2016
1,0.0,0.391304,0.323529,0.433333,0.275862,0.348485,0.351544,0.272727,0.234375,0.241379,...,0.047,0.300839,0.020513,0.203791,0.290323,0.375000,0.0,False,ATL,2016
2,0.0,0.413043,0.500000,0.321429,0.310345,0.378788,0.368171,0.227273,0.265625,0.379310,...,0.140,0.509434,0.161538,0.345972,0.290323,0.294643,1.0,False,CLE,2016
3,0.0,0.391304,0.397059,0.371429,0.241379,0.227273,0.437055,0.363636,0.359375,0.241379,...,0.185,0.270440,0.089744,0.232227,0.301075,0.276786,0.0,True,CHI,2016
4,0.0,0.347826,0.338235,0.364286,0.206897,0.212121,0.395487,0.431818,0.421875,0.275862,...,0.079,0.679245,0.278205,0.554502,0.290323,0.419643,1.0,False,NOP,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,0.0,0.456522,0.500000,0.373810,0.482759,0.424242,0.520190,0.590909,0.500000,0.655172,...,0.070,1.000000,0.130769,0.668246,0.634409,0.401786,0.0,True,OKC,2025
25680,0.0,0.260870,0.205882,0.357143,0.275862,0.393939,0.317102,0.477273,0.406250,0.137931,...,0.083,1.000000,0.082051,0.417062,0.268817,0.392857,1.0,False,OKC,2025
25681,0.0,0.413043,0.470588,0.342857,0.517241,0.575758,0.423990,0.386364,0.390625,0.379310,...,0.313,0.351153,0.283333,0.459716,0.397849,0.241071,0.0,True,IND,2025
25682,0.0,0.217391,0.147059,0.345238,0.379310,0.363636,0.466746,0.500000,0.453125,0.413793,...,0.183,1.000000,0.779487,0.345972,0.397849,0.348214,1.0,False,IND,2025
25683,0.0,0.347826,0.397059,0.316667,0.379310,0.545455,0.326603,0.500000,0.484375,0.448276,...,0.067,0.509434,0.262821,0.213270,0.494624,0.241071,0.0,True,OKC,2025

In [290]:
def find_team_averages(team):
    rolling = team[selected_columns].rolling(10).mean()
    return rolling


df_rolling = df_rolling.groupby(["team","season"], group_keys=False).apply(find_team_averages)

C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\2545853809.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_rolling = df_rolling.groupby(["team","season"], group_keys=False).apply(find_team_averages)

In [291]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,0.0,0.473913,0.400000,0.475952,0.400000,0.403030,0.449406,0.509091,0.418750,0.379310,...,0.113377,0.492546,0.0579,0.0841,0.405660,0.137821,0.480569,0.523656,0.411607,0.4
25680,0.0,0.452174,0.388235,0.456667,0.389655,0.416667,0.418884,0.509091,0.418750,0.362069,...,0.118969,0.450917,0.0625,0.0867,0.471174,0.119359,0.503791,0.498925,0.429464,0.5
25681,0.0,0.421739,0.333824,0.462619,0.424138,0.445455,0.430998,0.484091,0.421875,0.303448,...,0.180592,0.332913,0.0641,0.1075,0.315933,0.202821,0.563507,0.461290,0.417857,0.4
25682,0.0,0.410870,0.323529,0.455952,0.444828,0.450000,0.453919,0.472727,0.415625,0.324138,...,0.179276,0.365023,0.0663,0.1183,0.385849,0.260769,0.541706,0.463441,0.415179,0.5
25683,0.0,0.430435,0.383824,0.433333,0.396552,0.427273,0.419121,0.515909,0.429688,0.375862,...,0.123904,0.451147,0.0641,0.0861,0.492034,0.132308,0.497630,0.493548,0.418750,0.5

In [294]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols
df= pd.concat([df, df_rolling], axis=1)

In [296]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,trb%_max_opp_10,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10
0,0.0,0.391304,0.529412,0.276190,0.413793,0.378788,0.491686,0.454545,0.406250,0.793103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.391304,0.323529,0.433333,0.275862,0.348485,0.351544,0.272727,0.234375,0.241379,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.413043,0.500000,0.321429,0.310345,0.378788,0.368171,0.227273,0.265625,0.379310,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.391304,0.397059,0.371429,0.241379,0.227273,0.437055,0.363636,0.359375,0.241379,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.347826,0.338235,0.364286,0.206897,0.212121,0.395487,0.431818,0.421875,0.275862,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,0.0,0.456522,0.500000,0.373810,0.482759,0.424242,0.520190,0.590909,0.500000,0.655172,...,0.113377,0.492546,0.0579,0.0841,0.405660,0.137821,0.480569,0.523656,0.411607,0.4
25680,0.0,0.260870,0.205882,0.357143,0.275862,0.393939,0.317102,0.477273,0.406250,0.137931,...,0.118969,0.450917,0.0625,0.0867,0.471174,0.119359,0.503791,0.498925,0.429464,0.5
25681,0.0,0.413043,0.470588,0.342857,0.517241,0.575758,0.423990,0.386364,0.390625,0.379310,...,0.180592,0.332913,0.0641,0.1075,0.315933,0.202821,0.563507,0.461290,0.417857,0.4
25682,0.0,0.217391,0.147059,0.345238,0.379310,0.363636,0.466746,0.500000,0.453125,0.413793,...,0.179276,0.365023,0.0663,0.1183,0.385849,0.260769,0.541706,0.463441,0.415179,0.5
25683,0.0,0.347826,0.397059,0.316667,0.379310,0.545455,0.326603,0.500000,0.484375,0.448276,...,0.123904,0.451147,0.0641,0.0861,0.492034,0.132308,0.497630,0.493548,0.418750,0.5

In [298]:
df = df.dropna()

In [300]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,trb%_max_opp_10,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10
243,0.0,0.500000,0.382353,0.521429,0.344828,0.333333,0.457245,0.272727,0.250000,0.275862,...,0.152851,0.311927,0.0628,0.0679,0.413522,0.125256,0.361611,0.410753,0.322321,0.4
249,0.0,0.630435,0.426471,0.642857,0.620690,0.515152,0.562945,0.340909,0.250000,0.206897,...,0.166667,0.412271,0.0613,0.0772,0.469497,0.220641,0.394787,0.486022,0.300893,0.5
252,0.0,0.326087,0.250000,0.411905,0.310345,0.257576,0.509501,0.522727,0.421875,0.448276,...,0.132675,0.458257,0.0699,0.1072,0.380294,0.274359,0.270616,0.437634,0.286607,0.6
255,0.0,0.282609,0.235294,0.361905,0.344828,0.348485,0.439430,0.636364,0.484375,0.344828,...,0.135965,0.398280,0.0747,0.0742,0.303564,0.131667,0.387678,0.375269,0.325893,0.5
259,0.0,0.217391,0.279412,0.233333,0.310345,0.348485,0.395487,0.386364,0.328125,0.344828,...,0.195285,0.314220,0.0620,0.0626,0.373480,0.142436,0.320379,0.392473,0.318750,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,0.0,0.456522,0.500000,0.373810,0.482759,0.424242,0.520190,0.590909,0.500000,0.655172,...,0.113377,0.492546,0.0579,0.0841,0.405660,0.137821,0.480569,0.523656,0.411607,0.4
25680,0.0,0.260870,0.205882,0.357143,0.275862,0.393939,0.317102,0.477273,0.406250,0.137931,...,0.118969,0.450917,0.0625,0.0867,0.471174,0.119359,0.503791,0.498925,0.429464,0.5
25681,0.0,0.413043,0.470588,0.342857,0.517241,0.575758,0.423990,0.386364,0.390625,0.379310,...,0.180592,0.332913,0.0641,0.1075,0.315933,0.202821,0.563507,0.461290,0.417857,0.4
25682,0.0,0.217391,0.147059,0.345238,0.379310,0.363636,0.466746,0.500000,0.453125,0.413793,...,0.179276,0.365023,0.0663,0.1183,0.385849,0.260769,0.541706,0.463441,0.415179,0.5
25683,0.0,0.347826,0.397059,0.316667,0.379310,0.545455,0.326603,0.500000,0.484375,0.448276,...,0.123904,0.451147,0.0641,0.0861,0.492034,0.132308,0.497630,0.493548,0.418750,0.5

In [302]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1688004556.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1688004556.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "home")
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1688004556.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1688004556.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df, "team_opp")
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1688004556.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))
C:\Users\Schoo\AppData\Local\Temp\ipykernel_30736\1688004556.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [304]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,home_next,team_opp_next,date_next
243,0.0,0.500000,0.382353,0.521429,0.344828,0.333333,0.457245,0.272727,0.250000,0.275862,...,0.0679,0.413522,0.125256,0.361611,0.410753,0.322321,0.4,0.0,BOS,2015-11-13
249,0.0,0.630435,0.426471,0.642857,0.620690,0.515152,0.562945,0.340909,0.250000,0.206897,...,0.0772,0.469497,0.220641,0.394787,0.486022,0.300893,0.5,1.0,BRK,2015-11-14
252,0.0,0.326087,0.250000,0.411905,0.310345,0.257576,0.509501,0.522727,0.421875,0.448276,...,0.1072,0.380294,0.274359,0.270616,0.437634,0.286607,0.6,0.0,SAC,2015-11-15
255,0.0,0.282609,0.235294,0.361905,0.344828,0.348485,0.439430,0.636364,0.484375,0.344828,...,0.0742,0.303564,0.131667,0.387678,0.375269,0.325893,0.5,0.0,WAS,2015-11-14
259,0.0,0.217391,0.279412,0.233333,0.310345,0.348485,0.395487,0.386364,0.328125,0.344828,...,0.0626,0.373480,0.142436,0.320379,0.392473,0.318750,0.5,1.0,NOP,2015-11-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25679,0.0,0.456522,0.500000,0.373810,0.482759,0.424242,0.520190,0.590909,0.500000,0.655172,...,0.0841,0.405660,0.137821,0.480569,0.523656,0.411607,0.4,0.0,IND,2025-06-19
25680,0.0,0.260870,0.205882,0.357143,0.275862,0.393939,0.317102,0.477273,0.406250,0.137931,...,0.0867,0.471174,0.119359,0.503791,0.498925,0.429464,0.5,1.0,IND,2025-06-22
25681,0.0,0.413043,0.470588,0.342857,0.517241,0.575758,0.423990,0.386364,0.390625,0.379310,...,0.1075,0.315933,0.202821,0.563507,0.461290,0.417857,0.4,0.0,OKC,2025-06-22
25682,0.0,0.217391,0.147059,0.345238,0.379310,0.363636,0.466746,0.500000,0.453125,0.413793,...,0.1183,0.385849,0.260769,0.541706,0.463441,0.415179,0.5,NaN,None,None
25683,0.0,0.347826,0.397059,0.316667,0.379310,0.545455,0.326603,0.500000,0.484375,0.448276,...,0.0861,0.492034,0.132308,0.497630,0.493548,0.418750,0.5,NaN,None,None

In [306]:
df = df.copy()

In [308]:
full = df.merge(df[rolling_cols + ["team_opp_next", "date_next", "team"]], 
                left_on=["team", "date_next"],
                right_on=["team_opp_next", "date_next"] )

In [310]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,stl%_max_opp_10_y,blk%_max_opp_10_y,tov%_max_opp_10_y,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,team_opp_next_y,team_y
0,0.0,0.326087,0.250000,0.411905,0.310345,0.257576,0.509501,0.522727,0.421875,0.448276,...,0.0657,0.1032,0.437212,0.126026,0.404739,0.373118,0.398214,0.2,TOR,SAC
1,0.0,0.456522,0.500000,0.373810,0.379310,0.348485,0.483373,0.454545,0.406250,0.517241,...,0.0699,0.1072,0.380294,0.274359,0.270616,0.437634,0.286607,0.6,SAC,TOR
2,0.0,0.304348,0.323529,0.316667,0.275862,0.272727,0.432304,0.204545,0.171875,0.206897,...,0.0574,0.0839,0.310377,0.128205,0.312796,0.375269,0.328571,0.5,PHI,DAL
3,0.0,0.413043,0.397059,0.400000,0.137931,0.212121,0.263658,0.431818,0.375000,0.206897,...,0.0389,0.0726,0.468868,0.124231,0.332227,0.372043,0.343750,0.5,ORL,MIN
4,0.0,0.326087,0.558824,0.185714,0.206897,0.469697,0.203088,0.159091,0.125000,0.310345,...,0.0616,0.0766,0.413732,0.157821,0.470142,0.358065,0.405357,0.6,DEN,NOP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22841,0.0,0.326087,0.294118,0.371429,0.379310,0.484848,0.363420,0.568182,0.515625,0.241379,...,0.0576,0.0814,0.345807,0.129615,0.458294,0.518280,0.397321,0.4,IND,OKC
22842,0.0,0.391304,0.323529,0.433333,0.379310,0.393939,0.435867,0.545455,0.468750,0.620690,...,0.0579,0.0841,0.405660,0.137821,0.480569,0.523656,0.411607,0.4,IND,OKC
22843,0.0,0.456522,0.500000,0.373810,0.482759,0.424242,0.520190,0.590909,0.500000,0.655172,...,0.0630,0.0855,0.311635,0.194103,0.548815,0.479570,0.433929,0.5,OKC,IND
22844,0.0,0.260870,0.205882,0.357143,0.275862,0.393939,0.317102,0.477273,0.406250,0.137931,...,0.0641,0.1075,0.315933,0.202821,0.563507,0.461290,0.417857,0.4,OKC,IND
22845,0.0,0.413043,0.470588,0.342857,0.517241,0.575758,0.423990,0.386364,0.390625,0.379310,...,0.0625,0.0867,0.471174,0.119359,0.503791,0.498925,0.429464,0.5,IND,OKC

In [312]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        TOR             SAC    SAC             TOR  2015-11-15
1        SAC             TOR    TOR             SAC  2015-11-15
2        PHI             DAL    DAL             PHI  2015-11-16
3        ORL             MIN    MIN             ORL  2015-11-18
4        DEN             NOP    NOP             DEN  2015-11-17
...      ...             ...    ...             ...         ...
22841    IND             OKC    OKC             IND  2025-06-16
22842    IND             OKC    OKC             IND  2025-06-19
22843    OKC             IND    IND             OKC  2025-06-19
22844    OKC             IND    IND             OKC  2025-06-22
22845    IND             OKC    OKC             IND  2025-06-22

[22846 rows x 5 columns]

In [314]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [316]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [318]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [ ]:
sfs.fit(full[selected_columns], full["target"])

In [ ]:
predictors = list(selected_columns[sfs.get_support()])

In [ ]:
predictors

In [198]:
predictions = backtest(full, rr, predictors)

In [200]:
accuracy_score(predictions["actual"], predictions["prediction"])

0.6408098146008693